'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Phone, MessageCircle, Check, Sparkles, House, Building2, Shirt, Sofa, PaintRoller, CalendarDays, Clock3, MapPin, Menu, X, ChevronDown } from 'lucide-react';

const phone = 'tel:+233548818011';
const whatsapp = 'https://wa.me/233548818011';
const services = [
 {icon:House,name:'Home & deep cleaning',text:'From everyday upkeep to the corners that need extra care. A fresh start for your whole home.'},
 {icon:Building2,name:'Office & commercial',text:'Welcoming workplaces, shops and shared spaces, with a cleaning schedule built around your business.'},
 {icon:Shirt,name:'Laundry & ironing',text:'Freshly washed, neatly finished clothes and linens. Tell us what needs care and we’ll discuss the details.'},
 {icon:Sofa,name:'Sofa & carpet care',text:'Focused cleaning for upholstery, carpets and rugs, with the approach matched to the material.'},
 {icon:PaintRoller,name:'Post-construction',text:'Clear away the dust and residue after building or renovation, and get your space ready to use.'},
 {icon:CalendarDays,name:'Move-in & event cleaning',text:'Before a new chapter or after a busy occasion. Cleaning for moves, gatherings and property handovers.'},
];
const faqs = [
 ['Where do you work?','We are based in Winneba and serve homes and businesses across Ghana’s Central Region. Share your town and location so we can confirm travel arrangements and availability.'],
 ['How much does a cleaning cost?','Every space is different. Your quote depends on the service, property size, condition, location and frequency. Send your details for a tailored quote before you decide.'],
 ['Can I book a service at night or on a weekend?','We offer 24/7 service availability. Send your preferred date and time; our team will confirm a suitable slot before your booking is final.'],
 ['Do you offer regular corporate cleaning?','Yes. We can discuss recurring cleaning for offices, schools, churches, hostels, hospitality spaces and shops. Request a site assessment and a schedule suited to your operations.'],
 ['What happens after I request a quote?','The form prepares a WhatsApp message with your service details. Send it to Pinii, then our team will discuss the scope, price and availability. A request is not a confirmed booking.'],
 ['Should I provide cleaning supplies?','Tell us about your surfaces and any product preferences or allergies when requesting a quote. We will agree on the equipment, supplies and access arrangements before the service.'],
];
function Brand(){return <a className="brand" href="#home" aria-label="Pinii Cleaning and Laundry home"><span className="brand-mark"><Sparkles size={25}/></span><span>pinii<span className="brand-sub">CLEANING & LAUNDRY</span></span></a>}

export default function Home(){
 const [menu,setMenu]=useState(false); const [prepared,setPrepared]=useState('');
 const [selected,setSelected]=useState('Home & deep cleaning');
 const [today,setToday]=useState('');
 useEffect(()=>{setToday(new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Accra',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));},[]);
 function prepare(e){e.preventDefault(); const f=new FormData(e.currentTarget); const message=`Hello Pinii! I would like to request a quote.\n\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nService: ${selected}\nLocation: ${f.get('location')}\nPreferred date: ${f.get('date') || 'Flexible'}\nPreferred time: ${f.get('time')}\nFrequency: ${f.get('frequency')}\nDetails: ${f.get('details') || 'Please help me agree on the scope.'}\n\nPlease confirm price and availability.`; setPrepared(`${whatsapp}?text=${encodeURIComponent(message)}`); }
 function selectService(name){setSelected(name);setPrepared('');}
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <div className="topbar"><div className="wrap"><span><MapPin size={14}/> Winneba · Serving Central Region, Ghana</span><span><span className="status-dot"/> Available 24/7 <a href={phone}>054 881 8011</a></span></div></div>
 <header><div className="wrap nav"><Brand/><nav aria-label="Main navigation" className={menu?'nav-links open':'nav-links'}>{[['Services','services'],['Why Pinii','why-pinii'],['Our approach','gallery'],['For business','business'],['Contact','contact']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="button small nav-quote" href="#booking">Get a free quote <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="main">
 <section className="hero" id="home"><div className="wrap hero-grid"><div className="hero-copy"><p className="eyebrow"><span/> CLEAN SPACES. CLEAR MINDS.</p><h1>A cleaner space.<br/>A lighter <span>day.</span></h1><p className="hero-description">Leave the cleaning to us. From your living room to your workplace, Pinii brings a fresh feeling to spaces across Central Region.</p><div className="button-row"><a href="#booking" className="button">Book a cleaning <ArrowUpRight size={19}/></a><a href={whatsapp} className="button outline"><MessageCircle size={19}/> Let’s talk on WhatsApp</a></div><div className="hero-checks"><span><Check/> Personalised quotes</span><span><Check/> One-time or regular care</span></div></div><figure className="hero-visual"><img src="/hero.webp" alt="Illustration of a professional cleaner caring for a bright modern home" width="1536" height="1024" fetchPriority="high"/><div className="image-tag"><Sparkles size={24}/><span>A little care.<strong>A whole lot of fresh.</strong></span></div><figcaption>AI-generated brand illustration</figcaption></figure></div></section>
 <div className="service-strip"><div className="wrap"><span>HOMES</span><i/><span>WORKPLACES</span><i/><span>LAUNDRY</span><i/><span>COMMERCIAL SPACES</span><i/><span>24/7 AVAILABILITY</span></div></div>
 <section className="section wrap" id="services"><div className="section-heading"><div><p className="eyebrow">WHAT WE TAKE CARE OF</p><h2>Life gets busy.<br/>We get cleaning.</h2></div><p>One cleaning partner for your home, your clothes and your business. Choose what you need. We’ll take it from there.</p></div><div className="services-grid">{services.map((s,i)=><a href="#booking" onClick={()=>selectService(s.name)} className="service-card" key={s.name}><div className="card-top"><s.icon size={29} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{s.name}</h3><p>{s.text}</p><span className="text-link">Request this service <ArrowUpRight size={18}/></span></a>)}</div><p className="services-note">Something a little different? <a href={whatsapp}>Tell us about your space <ArrowRight size={16}/></a></p></section>
 <section className="why-section" id="why-pinii"><div className="wrap why-grid"><div><p className="eyebrow">THE PINII DIFFERENCE</p><h2>Care that fits<br/>your everyday.</h2><p className="section-intro">A great clean should feel easy, from your first conversation to the finishing touches.</p><a href="#booking" className="text-link">Let’s plan your clean <ArrowUpRight size={20}/></a></div><div className="reasons">{[['01','Your space, your priorities','We start with what matters to you and agree on the cleaning scope before getting to work.'],['02','A quote that makes sense','Affordable care, with a tailored quote based on the work you actually need.'],['03','Around your schedule','Early starts, evenings or weekends. Request a time that works for you, with 24/7 availability.'],['04','Local care, across the region','Based in Winneba, ready to discuss cleaning for homes and businesses throughout Central Region.']].map(([n,t,p])=><div className="reason" key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div><Check size={20}/></div>)}</div></div></section>
 <section className="section wrap" id="gallery"><div className="section-heading"><div><p className="eyebrow">A FRESH PERSPECTIVE</p><h2>Imagine the difference.</h2></div><p>From lived-in to ready for living. A visual look at the kind of transformation a thorough clean can bring.</p></div><figure className="comparison"><img src="/before-after.webp" alt="AI-generated comparison of the same living room before and after illustrative cleaning" width="1536" height="1024" loading="lazy"/><span className="before-label">BEFORE</span><span className="after-label">AFTER</span></figure><p className="gallery-note">Illustrative before-and-after gallery. These AI-generated images are not photographs of Pinii customer jobs or a guarantee of results.</p></section>
 <section className="business-section" id="business"><div className="wrap business-grid"><div><p className="eyebrow">FOR YOUR BUSINESS</p><h2>A better first impression.<br/><span>Every working day.</span></h2><p>Give your people a space they’re proud to walk into. We help you plan cleaning around your opening hours, footfall and the areas that matter most.</p><a className="button aqua" href="#booking" onClick={()=>selectService('Corporate cleaning contract')}>Discuss a corporate plan <ArrowUpRight size={19}/></a></div><div className="business-panel"><Building2 size={38} strokeWidth={1.3}/><h3>Your space. Our attention.</h3><ul>{['Offices & commercial buildings','Schools, churches & community spaces','Hostels, hotels & guest accommodation','Restaurants, shops & retail spaces'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><div>One-time deep cleans · Recurring cleaning · Site assessments</div></div></div></section>
 <section className="section wrap process"><p className="eyebrow">LESS TO DO. MORE TO ENJOY.</p><div className="section-heading"><h2>Fresh starts here.</h2><p>Three simple steps between you and a cleaner space.</p></div><div className="steps">{[['01','Tell us what you need','Choose a service and share your location, preferred timing and a few details.'],['02','Agree on the details','We’ll discuss your space, provide a quote and confirm a suitable appointment.'],['03','Enjoy your fresh start','Once your service is confirmed, we’ll agree on access and get your clean underway.']].map(([n,t,p])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div></section>
 <section className="booking-section" id="booking"><div className="wrap booking-grid"><div className="booking-copy"><p className="eyebrow">LET’S TAKE IT OFF YOUR LIST</p><h2>Your next clean<br/>starts with hello.</h2><p>Tell us a little about what you need. We’ll help you find the right service and a quote that fits your space.</p><div className="contact-line"><Phone/><div><span>Prefer a quick call?</span><a href={phone}>054 881 8011</a></div></div><div className="contact-line"><Clock3/><div><span>Here when you need us</span><strong>Available 24 hours, 7 days a week</strong></div></div><div className="coverage"><MapPin size={22}/><div><strong>Winneba & Central Region</strong><p>Share your town or neighbourhood. We’ll confirm availability and travel arrangements for your location.</p></div></div></div>
 <form onSubmit={prepare} onChange={()=>setPrepared('')} className="quote-form"><h3>Request your free quote</h3><p>No commitment. Let’s start with the details.</p><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required maxLength={100} placeholder="Full name"/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" pattern="[+0-9 ()-]{9,20}" title="Enter a phone number with 9–20 characters" required placeholder="e.g. 054 000 0000"/></label><label className="full">What can we help with?<select name="service" value={selected} onChange={e=>selectService(e.target.value)}>{services.map(s=><option key={s.name}>{s.name}</option>)}<option>Corporate cleaning contract</option><option>Other / custom cleaning</option></select></label><label className="full">Your location<input name="location" required autoComplete="address-level2" maxLength={200} placeholder="Town or neighbourhood in Central Region"/></label><label>Preferred date <span>(optional)</span><input name="date" type="date" min={today}/></label><label>Preferred time<select name="time"><option>Flexible — let’s discuss</option><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Overnight</option></select></label><label className="full">How often?<select name="frequency"><option>One-time service</option><option>Weekly</option><option>Fortnightly</option><option>Monthly</option><option>Let’s discuss a schedule</option></select></label><label className="full">Anything we should know? <span>(optional)</span><textarea name="details" maxLength={2000} rows={3} placeholder="Property size, items to clean, or special requests…"/></label></div><p className="form-note">Your details stay on this page until you choose to open WhatsApp. Send the prepared message there to request your quote. We’ll confirm pricing and availability before booking.</p><button className="button submit" type="submit">Prepare my quote request <ArrowRight size={19}/></button>{prepared&&<div className="ready-message" role="status"><strong>Your request is ready.</strong><p>Open WhatsApp, review the message and tap send. Your booking is not confirmed yet.</p><a className="button" href={prepared} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/> Open WhatsApp to send</a></div>}</form></div></section>
 <section className="section wrap faq" id="faq"><div><p className="eyebrow">GOOD TO KNOW</p><h2>A few fresh answers.</h2><p>Have something else in mind?<br/><a href={whatsapp}>Ask us on WhatsApp <ArrowUpRight size={17}/></a></p></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={20}/></summary><p>{a}</p></details>)}</div></section>
 <section className="closing"><div className="wrap"><div><p className="eyebrow">ONE LESS THING ON YOUR MIND</p><h2>Ready for that just-cleaned feeling?</h2></div><a className="button" href="#booking">Let’s get started <ArrowUpRight size={20}/></a></div></section>
 </main><footer id="contact"><div className="wrap footer-grid"><div><Brand/><p>Fresh spaces for everyday life.<br/>Cleaning & laundry in Central Region, Ghana.</p></div><div><h3>Explore</h3><a href="#services">Our services</a><a href="#business">Corporate cleaning</a><a href="#booking">Request a quote</a><a href="#faq">FAQs</a></div><div><h3>Say hello</h3><a href={phone}>054 881 8011</a><a href={whatsapp}>Chat on WhatsApp <ArrowUpRight size={15}/></a><p>Winneba, Central Region, Ghana<br/>Available 24/7</p></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Pinii Cleaning & Laundry</span><span>Made for a fresher everyday.</span></div></footer><a className="floating-whatsapp" href={whatsapp} aria-label="Chat with Pinii on WhatsApp"><MessageCircle size={25}/><span>Chat with us</span></a>
 </>;
}
